import type { Product } from "@/shared/types";

export const products: Product[] = [
  {
    id: 1,
    name: "My Journal",
    image_url: "/products/journals/my_journal/cover-new.png",
    price_range: "$10.50",
    type: "journal",
    date_added: "2026-06-05",
    available: true,
    store: "amazon",
    link: "https://www.amazon.com/My-Journal-N-Chambers/dp/B0BSJC3K6N?ref_=ast_author_dp_rw&th=1&psc=1&dib=eyJ2IjoiMSJ9.i8APTXifyVifJ_cxdsiaPG2w4D9ZIVo83pgQwRajGqzGjHj071QN20LucGBJIEps.AsQYRvKhbOv0Wgc3n69gc0cLQkRIhzakJWEWo6c2goo&dib_tag=AUTHOR",
    interiorImages: [
      { src: "/products/journals/my_journal/page1.jpeg", alt: "My Journal — inside page 1" },
      { src: "/products/journals/my_journal/page2.jpeg", alt: "My Journal — inside page 2" },
      { src: "/products/journals/my_journal/page3.jpeg", alt: "My Journal — inside page 3" },
    ],
  },
  {
    id: 2,
    name: "Floral Journal",
    image_url: "/products/journals/floral_journal/cover-new.png",
    price_range: "$11.00",
    type: "journal",  
    date_added: "2026-06-05",
    available: true,
    store: "amazon",
    link: "https://www.amazon.com/Floral-Journal-N-Chambers/dp/B0CFZ9ZQTH?ref_=ast_author_dp_rw&th=1&psc=1&dib=eyJ2IjoiMSJ9.i8APTXifyVifJ_cxdsiaPG2w4D9ZIVo83pgQwRajGqzGjHj071QN20LucGBJIEps.AsQYRvKhbOv0Wgc3n69gc0cLQkRIhzakJWEWo6c2goo&dib_tag=AUTHOR",
    interiorImages: [
      { src: "/products/journals/floral_journal/page1.jpeg", alt: "Floral Journal — inside page 1" },
      { src: "/products/journals/floral_journal/page2.jpeg", alt: "Floral Journal — inside page 2" },
      { src: "/products/journals/floral_journal/page3.jpeg", alt: "Floral Journal — inside page 3" },
    ],
  },
 
  {
    id: 3,
    name: "Woods Journal",
    image_url: "/products/journals/my_journal_woods/cover-new.png",
    price_range: "$10.75",
    type: "journal",
    date_added: "2026-06-05",
    available: true,
    store: "amazon",
    link: "https://www.amazon.com/My-Journal-Woods-Version-Chambers/dp/B0BSJPYTJB?ref_=ast_author_dp_rw&dib=eyJ2IjoiMSJ9.i8APTXifyVifJ_cxdsiaPG2w4D9ZIVo83pgQwRajGqzGjHj071QN20LucGBJIEps.AsQYRvKhbOv0Wgc3n69gc0cLQkRIhzakJWEWo6c2goo&dib_tag=AUTHOR",
    interiorImages: [
      { src: "/products/journals/my_journal_woods/page1.jpeg", alt: "Woods Journal — inside page 1" },
      { src: "/products/journals/my_journal_woods/page2.jpeg", alt: "Woods Journal — inside page 2" },
      { src: "/products/journals/my_journal_woods/page3.jpeg", alt: "Woods Journal — inside page 3" },
    ],
  },
  {
    id: 4,
    name: "Floral Journal 2",
    image_url: "/products/journals/floral_journal_2/cover-new.png",
    price_range: "",
    type: "journal",  
    date_added: "2026-06-05",
    available: false,
    store: "amazon",
    interiorImages: [
      { src: "/products/journals/floral_journal_2/page1.jpeg", alt: "Floral Journal 2 — inside page 1" },
      { src: "/products/journals/floral_journal_2/page2.jpeg", alt: "Floral Journal 2 — inside page 2" },
      { src: "/products/journals/floral_journal_2/page3.jpeg", alt: "Floral Journal 2 — inside page 3" },
    ],
  },
  {
    id: 5,
    name: "Spiral Notebook - Ruled Line",
    image_url: "/products/notebooks/spiral/cover.png",
    price_range: "15.00",
    type: "notebook", 
    date_added: "2026-06-06",
    available: true,
    store: "etsy",
    link: "https://www.etsy.com/listing/4326072135/spiral-notebook-ruled-line?sr_prefetch=1&pf_from=shop_home&ref=shop_home_active_1&logging_key=52502438cac15d7442ab85c7fc3f97b1d3a0012d%3A4326072135",
    interiorImages: [
      { src: "/products/notebooks/spiral/page1.png", alt: "Spiral Notebook — inside page 1" },
      { src: "/products/notebooks/spiral/page2.png", alt: "Spiral Notebook — inside page 2" },
    ],
  },
  {
    id: 6,
    name: "Unisex Heavy Cottton Floral Themed Tee",
    image_url: "/products/tshirts/floral/cover.png",
    price_range: "21.99 - 29.99",
    type: "t-shirt",
    date_added: "2026-06-06",
    available: true,
    store: "etsy",
    link: "https://www.etsy.com/listing/4516132749/unisex-heavy-cotton-floral-themed-tee?sr_prefetch=1&pf_from=shop_home&ref=shop_home_active_4&logging_key=ebf930e5d0902dce06d90cf4a79a04d82ccc43b5%3A4516132749&variation1=6689311274",
    interiorImages: [
      { src: "/products/tshirts/floral/page1.png", alt: "Unisex Heavy Cotton Floral Themed Tee — Sport Grey" },
      { src: "/products/tshirts/floral/page2.png", alt: "Unisex Heavy Cotton Floral Themed Tee — Black" },
      { src: "/products/tshirts/floral/page3.png", alt: "Unisex Heavy Cotton Floral Themed Tee — Charcoal" },
      { src: "/products/tshirts/floral/page4.png", alt: "Unisex Heavy Cotton Floral Themed Tee — Royal" },
      { src: "/products/tshirts/floral/page5.png", alt: "Unisex Heavy Cotton Floral Themed Tee — Navy" },
      { src: "/products/tshirts/floral/page6.png", alt: "Unisex Heavy Cotton Floral Themed Tee — Maroon" },
      { src: "/products/tshirts/floral/page7.png", alt: "Unisex Heavy Cotton Floral Themed Tee — Light Blue" },
      { src: "/products/tshirts/floral/page8.png", alt: "Unisex Heavy Cotton Floral Themed Tee — Light Pink" },
    ],
  },
  {
    id: 7,
    name: "Floral Themed Design Tote Bag",
    image_url: "/products/totes/floral/cover.png",
    price_range: "23.99 - 28.98",
    type: "tote",
    date_added: "2026-06-06",
    available: true,
    store: "etsy",
    link: "https://www.etsy.com/listing/4516128496/floral-themed-design-tote-bag?sr_prefetch=1&pf_from=shop_home&ref=shop_home_active_5&logging_key=f1be1e1376b135aeda96f0204dfeff11b262347f%3A4516128496",
    interiorImages: [
      { src: "/products/totes/floral/page1.png", alt: "Floral Themed Design Tote Bag" },
      { src: "/products/totes/floral/page2.png", alt: "Floral Themed Design Tote Bag" },
      { src: "/products/totes/floral/page3.png", alt: "Floral Themed Design Tote Bag" },
      { src: "/products/totes/floral/page4.png", alt: "Floral Themed Design Tote Bag" },
    ],
  },
  {
    id: 8,
    name: "Ocean View Tough Phone Case",
    image_url: "/products/phone_cases/ocean_view/cover.png",
    price_range: "23.49 - 26.75",
    type: "phone case",
    date_added: "2026-06-06",
    available: true,
    store: "etsy",
    link: "https://www.etsy.com/listing/4516128868/ocean-view-tough-phone-case?sr_prefetch=1&pf_from=shop_home&ref=shop_home_active_2&logging_key=3e01f6d5c173c7b60cea83d7587c98c0709a0f52%3A4516128868",
    interiorImages: [
      { src: "/products/phone_cases/ocean_view/page1.png", alt: "Ocean View Tough Phone Case" },
      { src: "/products/phone_cases/ocean_view/page2.png", alt: "Ocean View Tough Phone Case" },
      { src: "/products/phone_cases/ocean_view/page3.png", alt: "Ocean View Tough Phone Case" },
    ],
  },
  {
    id: 9,
    name: "Forest Scene Slim Phone Case",
    image_url: "/products/phone_cases/forest_scene/cover.png",
    price_range: "18.34 - 24.99",
    type: "phone case",
    date_added: "2026-06-06",
    available: true,
    store: "etsy",
    link: "https://www.etsy.com/listing/4326072044/forest-scene-slim-phone-case-cute-gift?sr_prefetch=1&pf_from=shop_home&ref=shop_home_active_3&logging_key=2a74a36ceab858d2d439042505ee56562fcb85e6%3A4326072044",
    interiorImages: [
      { src: "/products/phone_cases/forest_scene/page1.png", alt: "Forest Scene Slim Phone Case" },
      { src: "/products/phone_cases/forest_scene/page2.png", alt: "Forest Scene Slim Phone Case" },
      { src: "/products/phone_cases/forest_scene/page3.png", alt: "Forest Scene Slim Phone Case" },
    ],
  },
];

export function getProductById(id: number): Product | undefined {
  return products.find((product) => product.id === id);
}
